- added HTML workflow activity functions for CSR approval - added general approval classes to server - fixed PostgreSQL driver to work out of the box - small fixed for Debian (especially server startup)
git-svn-id: https://openxpki.svn.sourceforge.net/svnroot/openxpki@467 95d9436f-6502-0410-902c-bd9569d1a17e

diff --git a/trunk/package/debian/core/libopenxpki-perl.postinst b/trunk/package/debian/core/libopenxpki-perl.postinst
--- a/trunk/package/debian/core/libopenxpki-perl.postinst
+++ b/trunk/package/debian/core/libopenxpki-perl.postinst
@@ -27,7 +27,7 @@ case "$1" in
     configure)
 	# check for an installed deployment
 	if [ -e /etc/init.d/openxpkid ]; then
-		/etc/init.d/openxpkid restart
+		/etc/init.d/openxpkid restart || echo "OpenXPKI daemon restart failed."
 	fi;
     ;;
 
diff --git a/trunk/package/debian/deployment/openxpki-deployment.openxpkid.init b/trunk/package/debian/deployment/openxpki-deployment.openxpkid.init
--- a/trunk/package/debian/deployment/openxpki-deployment.openxpkid.init
+++ b/trunk/package/debian/deployment/openxpki-deployment.openxpkid.init
@@ -88,7 +88,7 @@ case "$1" in
 	#	just the same as "restart".
 	#
 	echo -n "Restarting $DESC: $NAME"
-	d_stop
+	d_stop || echo -n " - stop failed but trying to start"
 	sleep 1
 	d_start
 	echo "."
