Makefile now checks if vergen tools exists. E.g. tarballs do not have it.
git-svn-id: https://openxpki.svn.sourceforge.net/svnroot/openxpki@651 95d9436f-6502-0410-902c-bd9569d1a17e

diff --git a/trunk/deployment/Makefile.in b/trunk/deployment/Makefile.in
--- a/trunk/deployment/Makefile.in
+++ b/trunk/deployment/Makefile.in
@@ -33,12 +33,10 @@ ADMUSER         = [% server.admuser %]
 ADMGROUP        = [% server.admgroup %]
 
 CONFIGFILE      = etc/templates/$(TEMPLATE)/openxpki.conf
+VERSION_FILE    = ./VERSION
 
 ###########################################################################
 # no user serviceable parts below this line
-
-VERSION=$(shell $(VERGEN) --format version)
-
 
 TOOLS_SRC = \
 	bin/openxpkiadm.in \
@@ -54,8 +52,19 @@ all: tools build-man
 
 install: makedirs installtemplates installbin postinstallhelp
 
+writeversion:
+	@( if [ -e $(VERGEN) ] ; then \
+		$(VERGEN) --format version > $(VERSION_FILE); \
+	fi )
+	@( if [ ! -e $(VERSION_FILE) ] ; then \
+		echo "Could not determine version" ; \
+		exit 1; \
+	fi )
 
-tools: $(TOOLS)
+readversion: writeversion
+VERSION=$(shell cat $(VERSION_FILE))
+
+tools: readversion $(TOOLS)
 
 $(TOOLS_DST): $(TOOLS_SRC) $(CONFIGFILE)
 	for file in $(TOOLS_DST) ; do \
@@ -99,7 +108,7 @@ clean:
 
 distclean: clean
 
-dist:
+dist: readversion
 	if [ -d openxpki-deployment-$(VERSION) ] ; then \
 		rm -rf openxpki-deployment-$(VERSION)/ ; \
 	fi
diff --git a/trunk/i18n/Makefile b/trunk/i18n/Makefile
--- a/trunk/i18n/Makefile
+++ b/trunk/i18n/Makefile
@@ -8,6 +8,7 @@ LANGS         = en_GB de_DE ru_RU
 PO_SOURCES   = $(LANGS:%=%/openxpki.po)
 MO_TRANSLATIONS = $(LANGS:%=%/$(MO_FILE))
 POT_SOURCES  = ../perl-modules ../clients ../deployment
+VERSION_FILE    = ./VERSION
 
 #---- variable settings above, rules below ----
 
@@ -55,8 +56,20 @@ test install clean distclean::
 distclean clean::
 	rm -f */*.po~
 
-dist:	VERSION=`$(VERGEN) --format version`
-dist:
+writeversion:
+	@( if [ -e $(VERGEN) ] ; then \
+		$(VERGEN) --format version > $(VERSION_FILE); \
+	fi )
+	@( if [ ! -e $(VERSION_FILE) ] ; then \
+		echo "Could not determine version" ; \
+		exit 1; \
+	fi )
+
+readversion: writeversion
+VERSION=$(shell cat $(VERSION_FILE))
+
+#dist:	VERSION=`$(VERGEN) --format version`
+dist: readversion
 	if [ -d openxpki-i18n-$(VERSION) ] ; then \
 		rm -rf openxpki-i18n-$(VERSION)/ ; \
 	fi
