oxi-install now supports usage as a Docker entrypoint
The script now accepts a command to be executed afterwards.

diff --git a/tools/testenv/oxi-install b/tools/testenv/oxi-install
--- a/tools/testenv/oxi-install
+++ b/tools/testenv/oxi-install
@@ -35,10 +35,11 @@ function _exit () {
 
 [[ "${@#--help}" != "$@" ]] && cat <<__HELP && exit 1
 SYNOPSIS
-    $(basename "$0") [OPTIONS]
+    $(basename "$0") [OPTIONS] [COMMAND]
 
 DESCRIPTION
-    $(cat "$0" | grep "[[:blank:]]#*[[:blank:]]*<info>" | cut -d ">" -f2 | sed s/'^[[:blank:]]*'//)
+    $(cat "$0" | grep "[[:blank:]]#*[[:blank:]]*<info>" | cut -d ">" -f2 | sed s/'^[[:blank:]]*'//).
+    If COMMAND is given then it is executed afterwards.
 
 OPTIONS
     --no-i18n
@@ -48,7 +49,7 @@ OPTIONS
         Skip compiling XS code parts.
 
     --fast
-        Shortcut for "--no-i18n --no-compile --no-dbconfig".
+        Shortcut for "--no-i18n --no-compile".
 __HELP
 
 trap '_exit $?' EXIT
@@ -57,15 +58,42 @@ set -e
 #
 # Command line options
 #
+PARAMS=""
 IS_I18N=1
 IS_COMPILE=1
-# Bash string manipulation: use # to strip text off $@ and see if string still equals original $@
-[[ "${@#--no-i18n}" != "$@" ]]    && IS_I18N=0
-[[ "${@#--no-compile}" != "$@" ]] && IS_COMPILE=0
-[[ "${@#--fast}" != "$@" ]]       && IS_COMPILE=0 && IS_I18N=0
+while (( "$#" )); do
+    case "$1" in
+        --no-i18n)
+            IS_I18N=0
+            shift
+        ;;
+        --no-compile)
+            IS_COMPILE=0
+            shift
+            ;;
+        --fast)
+            IS_I18N=0
+            IS_COMPILE=0
+            shift
+            ;;
+        -*|--*=) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2
+            exit 0
+            ;;
+        *) # preserve all remaining arguments as positional arguments
+            PARAMS="$@"
+            break
+            ;;
+    esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
+
+FOLLOWUP_COMMAND="$@"
 
 echo "[$([ "$IS_COMPILE" -eq 1 ] && echo "X" || echo " ")] Compile OpenXPKI"
 echo "[$([ "$IS_I18N" -eq 1 ] && echo "X" || echo " ")] Compile i18n"
+test -n "$FOLLOWUP_COMMAND" && echo "[X] Execute: $FOLLOWUP_COMMAND"
 echo
 
 #
@@ -181,4 +209,9 @@ if [[ $IS_I18N -eq 1 ]]; then
 
         locale-gen                                                        >>$LOG 2>&1
     fi
+fi
+
+if [ -n "$FOLLOWUP_COMMAND" ]; then
+    echo "- execute $FOLLOWUP_COMMAND"
+    eval $FOLLOWUP_COMMAND
 fi
