improved deployment process to honour instance specific configuration
git-svn-id: https://openxpki.svn.sourceforge.net/svnroot/openxpki@347 95d9436f-6502-0410-902c-bd9569d1a17e

diff --git a/trunk/deployment/bin/openxpki-configure.in b/trunk/deployment/bin/openxpki-configure.in
--- a/trunk/deployment/bin/openxpki-configure.in
+++ b/trunk/deployment/bin/openxpki-configure.in
@@ -15,6 +15,7 @@ SYSCONFDIR="[% dir.sysconfdir %]"
 OPENXPKICONFDIR="[% dir.openxpkiconfdir %]"
 
 INTERACTIVE=1
+CREATE_DIRS=""
 FORCE=""
 
 
@@ -26,7 +27,7 @@ reconfigure() {
 
 write_config() {
     echo
-    echo "Creating configuration files in $OPENXPKICONFDIR"
+    echo "* Creating configuration files in $OPENXPKICONFDIR"
     for xmlfile in $* ; do
 	basename=`basename $xmlfile`
 	echo -n "$basename... "
@@ -40,6 +41,34 @@ write_config() {
 	    exit 1
 	fi
     done
+}
+
+# if no arguments are given this function only checks if the required
+# directories are present. otherwise these directories are also created
+check_dirs() {
+    echo
+    echo "* Checking directories"
+    error=0
+    for entry in openxpkistatedir openxpkisessiondir ; do
+	dir="`$CFG --getcfg dir.$entry`"
+	echo -n "$entry: "
+	if [ -d "$dir" ] ; then
+	    echo "$dir: OK"
+	else
+	    if [ "$1" != "" ] ; then
+		if install -o $RUNUSER -g $RUNGROUP -m 0750 -d $dir ; then
+		    echo "$dir: CREATED"
+		else
+		    echo "$dir: FAILED TO CREATE"
+		    error=1
+		fi
+	    else
+		echo "$dir: DOES NOT EXIST"
+		error=1
+	    fi
+	fi
+    done
+    return $error
 }
 
 
@@ -68,6 +97,10 @@ while [ -n "$1" ] ; do
 	    TEMPLATE="$1"
 	    shift
 	    ;;
+	--createdirs)
+	    CREATE_DIRS=1
+	    shift
+	    ;;
         --)
             shift
             METACONF_OPTS="$*"
@@ -83,7 +116,7 @@ while [ -n "$1" ] ; do
     esac
 done
 
-for DIR in /etc/openxpki /usr/local/etc/openxpki "$OPENXPKICONFDIR" "`pwd`"; do
+for DIR in /etc/openxpki /usr/local/etc/openxpki "$OPENXPKICONFDIR" "`pwd`/etc/openxpki" "`pwd`"; do
     if [ -e "$DIR/openxpki.conf" ]; then
 	OPENXPKICONFDIR="$DIR"
     fi
@@ -100,7 +133,9 @@ if [ "$INTERACTIVE" = "1" ] ; then
     fi
 fi
 
-XMLSTYLE="`$CFG --getcfg deployment.xmlstyle `"
+XMLSTYLE="`$CFG --getcfg deployment.xmlstyle`"
+RUNUSER="`$CFG --getcfg server.runuser`"
+RUNGROUP="`$CFG --getcfg server.rungroup`"
 
 FILES="$TEMPLATEDIR/$TEMPLATE/log.conf"
 
@@ -121,6 +156,21 @@ esac
 
 write_config $FILES
 
+if ! check_dirs $CREATE_DIRS ; then
+    echo
+    echo "One or more required directories do not exist. Please inspect the above"
+    echo "error output and either create the missing directories or run"
+    echo
+    echo "$0 [OPTIONS] --createdirs"
+    echo
+    echo "to automatically create them."
+    echo
+    exit 1
+fi
+
+echo
+echo "OpenXPKI instance configured successfully."
+
 exit 0
 
 ###########################################################################
@@ -137,6 +187,9 @@ openxpki-configure [OPTIONS]
     --help         display this help text and exit
     --batch        non-interactive configuration
     --force        overwrite existing files
+    --template     specify template (default: default)
+    --createdirs   create missing directories
+    --             args following -- are literally passed to openxpki-metaconf
 
 This script generates the OpenXPKI configuration files from a set of
 templates (taken from $TEMPLATEDIR)
diff --git a/trunk/deployment/configure b/trunk/deployment/configure
--- a/trunk/deployment/configure
+++ b/trunk/deployment/configure
@@ -41,16 +41,43 @@ EOF
 
 
 METACONF_OPTS=""
-if [ "`id -nu`" != "root" ] ; then
-    USER=`id -nu`
-    GROUP=`id -ng`
-    echo "Preparing for non-root installation (user: $USER, group: $GROUP)"
-    METACONF_OPTS="$METACONF_OPTS --setcfg server.runuser=$USER"
-    METACONF_OPTS="$METACONF_OPTS --setcfg server.rungroup=$GROUP"
-    METACONF_OPTS="$METACONF_OPTS --setcfg server.admuser=$USER"
-    METACONF_OPTS="$METACONF_OPTS --setcfg server.admgroup=$GROUP"
+
+# check infrastructure
+ERRORS=0
+echo "Checking required OpenXPKI Perl modules..."
+for module in OpenXPKI OpenXPKI::Client ; do
+    echo -n "$module: "
+    if perl -e "use $module;" >/dev/null 2>&1 ; then
+	echo "OK"
+    else
+	echo "NOT FOUND"
+	ERRORS=1
+    fi
+done
+
+if [ "$ERRORS" != "0" ] ; then
+    echo "Pre-installation check found errors."
+    echo "Please install the missing Perl modules before proceeding."
+    exit 1
 fi
 
+
+USER=`id -nu`
+GROUP=`id -ng`
+
+ADMUSER="$USER"
+ADMGROUP="$GROUP"
+if [ "$USER" != "root" ] ; then
+    echo "Preparing for non-root installation (user: $USER, group: $GROUP)"
+    RUNUSER="$USER"
+    RUNGROUP="$GROUP"
+fi
+
+
+[ -n "$RUNUSER" ] && METACONF_OPTS="$METACONF_OPTS --setcfg server.runuser=$RUNUSER"
+[ -n "$RUNGROUP" ] && METACONF_OPTS="$METACONF_OPTS --setcfg server.rungroup=$RUNGROUP"
+METACONF_OPTS="$METACONF_OPTS --setcfg server.admuser=$ADMUSER"
+METACONF_OPTS="$METACONF_OPTS --setcfg server.admgroup=$ADMGROUP"
 
 while [ -n "$1" ] ; do
     case "$1" in
